Rat/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.views import static as ds



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.home, name='home'),
    path('rat_s/', include('rat_s.urls')),

    re_path(r'^media/(?P<path>.*)$', ds.serve,
            {'document_root': settings.MEDIA_ROOT, }, name="media"),
] 
urlpatterns  +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    

rat_s/urls.py
from django.urls import path
from . import views
from .views import generate_pdf

app_name = 'rat_s'


urlpatterns = [
    path('', views.cadastrar_prestador_view, name='rat_s'),
    path('gerar_pdf/', views.generate_pdf, name='generate_pdf'),

]

rat_s_old/urls.py
from django.urls import path
from . import views
from .views import generate_pdf
from .views import MedicoSelectView

app_name = 'rat_s'


urlpatterns = [
    path('', views.cadastrar_prestador_view, name='rat_s'),
    path('gerar_pdf/', views.generate_pdf, name='generate_pdf'),
    path('medico-autocomplete/', MedicoSelectView.as_view(), name='medico-autocomplete'),


]

rat_s/models.py
from __future__ import unicode_literals
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User
from Rat import settings




class DadosPessoais(models.Model):

	nm_analista = models.CharField(verbose_name="Nome Profissional", max_length=50, default='')
	nm_medico = models.CharField(verbose_name="Nome Médico", max_length=100, blank=True, null=True)
	nm_hospital = models.CharField(verbose_name="Nome do Hospital", max_length=100, blank=True, null=True)
	tel_contato = models.CharField(verbose_name="Telefone Contato", max_length=100, blank=True, null=True)
	email = models.EmailField(verbose_name="Email", max_length=200, blank=True, null=True)
	dt_atendimento = models.DateTimeField(verbose_name="Data do atendimento", blank=True, null=True)
	servico_analisado= models.TextField(blank=True, null=True,verbose_name="Tipo de validação")
	upload = models.FileField(blank=True, null=True, upload_to='dados/')
	utiliza_protocolo = models.IntegerField(choices=((1, 'SIM'), (2, 'NÃO')), null=True, verbose_name="Utiliza protocolo gerenciavel ?")
	utiliza_rotina_especial = models.IntegerField(choices=((1, 'SIM'), (2, 'NÃO')), null=True, verbose_name="Utiliza rotina especial ?")
	utiliza_rotina = models.IntegerField(choices=((1, 'SIM'), (2, 'NÃO')), null=True, verbose_name="Utiliza rotina ?")
	comentarios = models.TextField(blank=True, null=True,verbose_name="Comentarios")
	data_insercao = models.DateTimeField(auto_now_add=True)
	
	def __str__(self):
		return f"{self.nm_medico} | {self.nm_hospital} | {self.servico_analisado}" 
	
	def upload_to(instance, filename):
		now = timezone_now()
		filename_base, filename_ext = os.path.splitext(filename)
		return "quotes/%s%s" % (
			now.strftime("%Y/%m/%Y%m%d%H%M%S"),
			filename_ext.lower(),
			)
    

rat_s_old/models.py
from __future__ import unicode_literals
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User
from Rat import settings


class Medico(models.Model):
    id = models.AutoField(primary_key=True, auto_created=True)
    nm_medico = models.CharField(max_length=200, blank=True, null=True)
    crm = models.CharField(max_length=200, verbose_name="Cod Conselho", blank=True, null=True)

    def __str__(self):
        return self.nm_medico

class DadosPessoais(models.Model):

	nm_analista = models.CharField(verbose_name="Nome Profissional", max_length=50, default='')
	nm_medico = models.ForeignKey(Medico, on_delete = models.SET_NULL, blank = True, null = True, verbose_name="Nome Medico")
	nm_hospital = models.CharField(verbose_name="Nome do Hospital", max_length=100, blank=True, null=True)
	tel_contato = models.CharField(verbose_name="Telefone Contato", max_length=100, blank=True, null=True)
	email = models.EmailField(verbose_name="Email", max_length=200, blank=True, null=True)
	dt_atendimento = models.DateTimeField(verbose_name="Data do atendimento", blank=True, null=True)
	servico_analisado= models.TextField(blank=True, null=True,verbose_name="Tipo de validação")
	upload = models.FileField(blank=True, null=True, upload_to='dados/')
	utiliza_protocolo = models.IntegerField(choices=((1, 'SIM'), (2, 'NÃO')), null=True, verbose_name="Utiliza protocolo gerenciavel ?")
	utiliza_rotina_especial = models.IntegerField(choices=((1, 'SIM'), (2, 'NÃO')), null=True, verbose_name="Utiliza rotina especial ?")
	utiliza_rotina = models.IntegerField(choices=((1, 'SIM'), (2, 'NÃO')), null=True, verbose_name="Utiliza rotina ?")
	comentarios = models.TextField(blank=True, null=True,verbose_name="Comentarios")
	data_insercao = models.DateTimeField(auto_now_add=True)
	
	def __str__(self):
		return f"{self.nm_analista} | {self.nm_hospital} | {self.data_insercao}" 
	
	def upload_to(instance, filename):
		now = timezone_now()
		filename_base, filename_ext = os.path.splitext(filename)
		return "quotes/%s%s" % (
			now.strftime("%Y/%m/%Y%m%d%H%M%S"),
			filename_ext.lower(),
			)
    

rat_s/forms.py
from django import forms
from .models import DadosPessoais

class DadosPessoaisForm(forms.ModelForm):
    class Meta:
        model = DadosPessoais
        fields = ['nm_analista', 'nm_medico', 'nm_hospital', 'tel_contato', 'email', 'dt_atendimento', 'servico_analisado', 'upload', 'utiliza_protocolo', 'utiliza_rotina_especial', 'utiliza_rotina', 'comentarios']
        widgets = {
            'upload': forms.ClearableFileInput(attrs={'multiple': True}),
        }

rat_s_old/forms.py
from django import forms
from django_select2.forms import ModelSelect2Mixin, Select2MultipleWidget
from .models import DadosPessoais

class DadosPessoaisForm(forms.ModelForm,ModelSelect2Mixin):
    class Meta:
        model = DadosPessoais
        fields = ['nm_analista', 'nm_medico', 'nm_hospital', 'tel_contato', 'email', 'dt_atendimento', 'servico_analisado', 'upload', 'utiliza_protocolo', 'utiliza_rotina_especial', 'utiliza_rotina', 'comentarios']
        widgets = {
            'upload': forms.ClearableFileInput(attrs={'multiple': True}),
            'nm_medico': Select2MultipleWidget,
        }
        search_fields = [
        'nm_medico__icontains',
        ]
        queryset = DadosPessoais.objects.all()

Rat/views.py
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.conf import settings
import json
User = settings.AUTH_USER_MODEL


def home(request):
    return render(request, template_name='home.html')

rat_s/views.py
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.pdfgen import canvas
from django.shortcuts import render
from django.http import HttpResponse
from io import BytesIO
from rat_s.models import DadosPessoais
from rat_s.forms import DadosPessoaisForm



def generate_pdf(request):
    # Obter os dados do formulário enviado
    height, width = letter

    nm_analista = request.POST.get('nm_analista', '')
    nm_medico = request.POST.get('nm_medico', '')
    nm_hospital = request.POST.get('nm_hospital', '')
    tel_contato = request.POST.get('tel_contato', '')
    email = request.POST.get('email', '')
    dt_atendimento = request.POST.get('dt_atendimento', '')
    servico_analisado = request.POST.get('servico_analisado', '')
    utiliza_protocolo = request.POST.get('utiliza_protocolo', '')
    utiliza_rotina_especial = request.POST.get('utiliza_rotina_especial', '')
    utiliza_rotina = request.POST.get('utiliza_rotina', '')
    comentarios = request.POST.get('comentarios', '')

    # Criar o PDF usando ReportLab
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="formulario.pdf"'

    # Cria um objeto PDF do ReportLab
    pdf = canvas.Canvas(response)

    # Adiciona o título do formulário
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(200, 750, "Formulário de Validação TASY|Matrix")

    # Adiciona os campos do formulário
    pdf.setFont("Helvetica", 10)
    pdf.drawString(50, 700, "Nome do Analista: {}".format(nm_analista))
    pdf.drawString(50, 670, "Nome do Médico: {}".format(nm_medico))
    pdf.drawString(50, 640, "Nome do Hospital: {}".format(nm_hospital))
    pdf.drawString(50, 610, "Telefone para contato: {}".format(tel_contato))
    pdf.drawString(50, 580, "E-mail: {}".format(email))
    pdf.drawString(50, 550, "Data do atendimento: {}".format(dt_atendimento))
    pdf.drawString(50, 520, "Serviço Analisado: {}".format(servico_analisado))
    pdf.drawString(50, 490, "Utiliza protocolo: {}".format(utiliza_protocolo))
    pdf.drawString(50, 460, "Utiliza rotina especial: {}".format(utiliza_rotina_especial))
    pdf.drawString(50, 430, "Utiliza rotina: {}".format(utiliza_rotina))
    # Divide o campo de comentários em linhas
    lines = comentarios.split('\n')
    y = 400
    for line in lines:
        pdf.drawString(50, y, "Comentário: {}".format(line))
        y -= 20


    # Salva o PDF
    pdf.save()

    return response    

def index(request):
    return render(request,'rat/index.html')   

def cadastrar_prestador_view(request):
    form = DadosPessoaisForm()

    if request.method == 'POST':
        form = DadosPessoaisForm(request.POST, request.FILES)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print('ERROR FORM')

    return render(request, 'rat/rat_s.html',{'form': form})

rat_s_old/views.py
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.pdfgen import canvas
from django.shortcuts import render
from django.http import HttpResponse
from io import BytesIO
from rat_s.models import DadosPessoais
from rat_s.forms import DadosPessoaisForm
from django_select2.views import Select2QuerySetView





def generate_pdf(request):
    # Obter os dados do formulário enviado
    height, width = letter

    nm_analista = request.POST.get('nm_analista', '')
    nm_medico = request.POST.get('nm_medico', '')
    nm_hospital = request.POST.get('nm_hospital', '')
    tel_contato = request.POST.get('tel_contato', '')
    email = request.POST.get('email', '')
    dt_atendimento = request.POST.get('dt_atendimento', '')
    servico_analisado = request.POST.get('servico_analisado', '')
    utiliza_protocolo = request.POST.get('utiliza_protocolo', '')
    utiliza_rotina_especial = request.POST.get('utiliza_rotina_especial', '')
    utiliza_rotina = request.POST.get('utiliza_rotina', '')
    comentarios = request.POST.get('comentarios', '')

    # Criar o PDF usando ReportLab
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="formulario.pdf"'

    # Cria um objeto PDF do ReportLab
    pdf = canvas.Canvas(response)

    # Adiciona o título do formulário
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(200, 750, "Formulário de Validação TASY|Matrix")

    # Adiciona os campos do formulário
    pdf.setFont("Helvetica", 10)
    pdf.drawString(50, 700, "Nome do Analista: {}".format(nm_analista))
    pdf.drawString(50, 670, "Nome do Médico: {}".format(nm_medico))
    pdf.drawString(50, 640, "Nome do Hospital: {}".format(nm_hospital))
    pdf.drawString(50, 610, "Telefone para contato: {}".format(tel_contato))
    pdf.drawString(50, 580, "E-mail: {}".format(email))
    pdf.drawString(50, 550, "Data do atendimento: {}".format(dt_atendimento))
    pdf.drawString(50, 520, "Serviço Analisado: {}".format(servico_analisado))
    pdf.drawString(50, 490, "Utiliza protocolo: {}".format(utiliza_protocolo))
    pdf.drawString(50, 460, "Utiliza rotina especial: {}".format(utiliza_rotina_especial))
    pdf.drawString(50, 430, "Utiliza rotina: {}".format(utiliza_rotina))
    # Divide o campo de comentários em linhas
    lines = comentarios.split('\n')
    y = 400
    for line in lines:
        pdf.drawString(50, y, "Comentário: {}".format(line))
        y -= 20


    # Salva o PDF
    pdf.save()

    return response    

def index(request):
    return render(request,'rat/index.html')   

class MedicoSelectView(Select2QuerySetView):
    def get_queryset(self):
        qs = DadosPessoais.objects.all()
        if self.q:
            qs = qs.filter(nm_medico__icontains=self.q)
        return qs


def cadastrar_prestador_view(request):
    form = DadosPessoaisForm()

    if request.method == 'POST':
        form = DadosPessoaisForm(request.POST, request.FILES)

        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print('ERROR FORM')

    return render(request, 'rat/rat_s.html',{'form': form})

rat_s_old/templates/rat/base - Copia.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}ROGTI{% endblock %}</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
        {% block content %}
        {% endblock %}
        <footer>
            <p>rogti</p>
        </footer>
    </div>
     <script
    src="https://code.jquery.com/jquery-3.4.0.min.js"
    integrity="sha256-BJeo0qm959uMBGb65z40ejJYGSgR7REI4+CW1fNKwOg="
    crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

rat_s_old/templates/rat/formulario_padrão.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ROGTi</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    
</head>

<style>
/*the container must be positioned relative:*/

</style>

<body>
  <div class="container-md mt-3 border">
    <div class="row">
  <h1>Formulario RAT!</h1>

  <form method="post" novalidate>{% csrf_token %}
    <div class="form-row">
      
      <div class="form-group col-md-5">
        <label>Consultor:</label>
          <input class="form-control" name="nm_profissional" id="id_nm_profissional" type="text">
      </div>
      <div class="form-group col-md-5">
        <label>Nome do Projeto:</label>
          <input class="form-control" name="nm_empresa" id="id_nm_empresa" type="text">
      </div>
      <div class="form-group col-md-5">
        <label>Cliente:</label>
          <input class="form-control" name="nm_cliente" id="id_nm_cliente" type="text">
      </div>
      <div class="form-group col-md-5">
        <label>Nome contato cliente:</label>
          <input class="form-control" name="nm_contato" id="id_nm_contato" type="text">
      </div>
      <div class="form-group col-md-5">
        <label>Telefone Cliente:</label>
          <input class="form-control" name="tel_contato" id="id_tel_contato" type="text">
      </div>
      <div class="form-group col-md-2">
        <label>Data Inicio:</label>
          <input class="form-control" name="dt_atendimento" id="id_dt_atendimento" type="date">
      </div>
      <div class="form-group col-md-2">
        <label>Data Fim:</label>
          <input class="form-control" name="dt_fim_atendimento" id="id_dt_fim_atendimento" type="date">
      </div>
      <div class="form-group col-md-2">
        <label>Intervalo inicial:</label>
          <input class="form-control" name="intervalo" id="id_intervalo" type="time">
          <small>Tempo de parada do intervalor</small>
      </div>
      <div class="form-group col-md-2">
        <label>Intervalo final:</label>
          <input class="form-control" name="intervalo_inicial" id="id_intervalo_inicial" type="time">
          <small>Tempo de parada do intervalor</small>
      </div>
      <div class="form-group col-md-5">
        <label>Servico Contratado:</label>
          <input class="form-control" name="servico_contratado" id="id_servico_contratado" type="text">
      </div>
      <div class="form-group col-md-2">
        <label>E-mail:</label>
          <input class="form-control" name="email" id="id_email" type="text">
      </div>
      <div class="form-group col-md-2">
        <label>Cidade:</label>
          <input class="form-control" name="cidade" id="id_cidade" type="text">
      </div>
      <div class="form-group col-md-5">
        <label>Endereco:</label>
          <input class="form-control" name="ds_endereco" id="id_ds_endereco" type="text">
      </div>
      <div class="form-group col-md-5">
        <label>Deslocamento ida:</label>
          <input class="form-control" name="deslocamento_ida" id="id_deslocamento_ida" type="text">
      </div>
      <div class="form-group col-md-5">
        <label>Deslocamento volta:</label>
          <input class="form-control" name="deslocamento_volta" id="id_deslocamento_volta" type="text">
      </div>
   
      <div class="form-group col-md-8">
        <label for="comentarios">Comentarios</label>
          <textarea class="form-control" rows="8" name="comentarios" id="id_comentarios"></textarea>
    </div>
    <div class="text-center">
      <div class="input-group input-group-lg">
          <input class="btn btn-outline-info" type="file" class="form-control-file border" name="upload" id="id_upload" accept="image/*"></input>
          <input class="btn btn-outline-info" type="file" class="form-control-file border" name="upload" id="id_upload" accept="image/*"></input>
        </div>
    </div>
        </form>

    </div> 
    <div class="content">
</div>
    <footer id="myFooter">
        <div class="container">
            <ul>
<div class="input-group input-group-lg">
  <div class="input-group-prepend">
    <span class="input-group-text" id="inputGroup-sizing-lg">Assinatura do Analista Rede D'Or</span>
  </div>
  <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg">
</div>

<div class="input-group input-group-lg">
  <div class="input-group-prepend">
    <span class="input-group-text" id="inputGroup-sizing-lg">Assinatura do Médico</span>
  </div>
  <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg">
</div>


                <li><a href="#">Terms of service</a></li>
            </ul>
        <p class="footer-copyright">© 2023 Copyright Thiago.fideles</p>
        </div>
<div id="data-hora"></div>

</footer>
<script>
      // Função para formatar 1 em 01
      const zeroFill = n => {
        return ('0' + n).slice(-2);
      }

      // Cria intervalo
      const interval = setInterval(() => {
        // Pega o horário atual
        const now = new Date();

        // Formata a data conforme dd/mm/aaaa hh:ii:ss
        const dataHora = zeroFill(now.getUTCDate()) + '/' + zeroFill((now.getMonth() + 1)) + '/' + now.getFullYear() + ' ' + zeroFill(now.getHours()) + ':' + zeroFill(now.getMinutes()) + ':' + zeroFill(now.getSeconds());

        // Exibe na tela usando a div#data-hora
        document.getElementById('data-hora').innerHTML = dataHora;
      }, 1000);
    </script>
</body>
</html>    


 

rat_s_old/templates/rat/rat_s.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <h3 class="text-center mb-7">Cadastro de solicitações rotinas e protocolos</h3>
            <form method="post" enctype="multipart/form-data" id="form-cadastro">
                {% csrf_token %}
                <div class="form-group">
                    <label for="{{ form.nm_analista.id_for_label }}">Nome Profissional</label>
                    {{ form.nm_analista|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="{{ form.nm_medico.id_for_label }}">Nome Médico</label>
                    {{ form.nm_medico|add_class:"form-control select2" }}
                </div>
                    
                <div class="form-group">
                    <label for="{{ form.nm_hospital.id_for_label }}">Nome do Hospital</label>
                    {{ form.nm_hospital|add_class:"form-control" }}
                </div>
                <div class="form-group row">
                <div class="col-sm-3">
                    <label for="{{ form.tel_contato.id_for_label }}">Telefone de Contato</label>
                    {{ form.tel_contato|add_class:"form-control" }}
                </div>
                
                <div class="form-group">
                    <div class="col-sm-10">
                        <label for="{{ form.email.id_for_label }}">Email</label>
                    {{ form.email|add_class:"form-control" }}
                    <small id="emailHelp" class="form-text text-muted">Enviar email para o solicitante.</small>
                  </div>
                </div>
                  
                <div class="form-group">
                    <div class="col-sm-12">
                        <label for="{{ form.dt_atendimento.id_for_label }}">Data do Atendimento</label>
                        {{ form.dt_atendimento|add_class:"form-control" }}
                        <small id="emailHelp" class="form-text text-muted">Data da reunião.</small>
                    </div>
                </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-5">
                    <label for="{{ form.servico_analisado.id_for_label }}">Tipo de Validação</label>
                    {{ form.servico_analisado|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <div class="col-sm-10">
                    <label for="{{ form.comentarios.id_for_label }}">Comentários</label>
                    {{ form.comentarios|add_class:"form-control" }}
                    </div>
                </div>
             </div>
             <div class="form-group row">
                <div class="form-check form-check-inline">
                    <div class="col-auto">
                  {{ form.utiliza_rotina_especial.label_tag }}
                  {{ form.utiliza_rotina_especial }}
                  <label class="form-check-label" for="{{ form.utiliza_rotina_especial.id_for_label }}">
                  </label>
                </div>
              </div>
              <div class="form-check form-check-inline">
                <div class="col-auto">
                  {{ form.utiliza_rotina.label_tag }}
                  {{ form.utiliza_rotina }}
                  <label class="form-check-label" for="{{ form.utiliza_rotina.id_for_label }}">
                  </label>
                </div>
              </div>
              <div class="form-check form-check-inline">
                <div class="col-auto">
                  {{ form.utiliza_protocolo.label_tag }}
                  {{ form.utiliza_protocolo }}
                  <label class="form-check-label" for="{{ form.utiliza_protocolo.id_for_label }}">
                  </label>
                </div>
              </div>
              </div>
                <div class="form-group">
                    <div class="col-sm-14">
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="inputGroupFile02" name="upload" multiple onchange="updateSelectedFiles()">
                        <label class="custom-file-label" for="inputGroupFile02">Selecione um ou mais arquivos</label>
                    </div>
                </div>
                </div>
                <div class="text-left">
                <ul class="list-group mt-3" id="selected-files">
                </ul>  
            </div>
              
                <div class="form-group text-center">
                    <button type="submit" formaction="{% url 'rat_s:generate_pdf' %}" class="btn btn-primary">Gerar PDF</button>
                </div>
                <div class="form-group text-center">
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
  $(document).ready(function() {
    $('form.nm_medico').select2();
  });
</script>
<script>
function updateSelectedFiles() {
  var fileInput = document.getElementById("inputGroupFile02");
  var files = fileInput.files;
  var fileList = document.getElementById("selected-files");
  
  // Crie uma nova lista para armazenar os arquivos selecionados
  var newFileList = [];
  
  for (var i = 0; i < files.length; i++) {
    var file = files[i];
    
    // Verifique se o arquivo já está na lista existente antes de adicioná-lo
    if (!fileListContains(fileList, file.name)) {
      // Adicione o arquivo à nova lista
      newFileList.push(file);
      
      // Crie um novo elemento de lista para o arquivo e adicione-o ao DOM
      var listItem = document.createElement("li");
      listItem.textContent = file.name;
      fileList.appendChild(listItem);
    }
  }
  
  // Adicione os itens existentes à nova lista
  var existingItems = fileList.getElementsByTagName("li");
  for (var i = 0; i < existingItems.length; i++) {
    var item = existingItems[i];
    newFileList.push(item.textContent);
  }
  
  // Atualize o valor do campo de upload com a nova lista de arquivos selecionados
  fileInput.value = newFileList.join(",");
}

function fileListContains(fileList, fileName) {
  var items = fileList.getElementsByTagName("li");
  for (var i = 0; i < items.length; i++) {
    var item = items[i];
    if (item.textContent == fileName) {
      return true;
    }
  }
  return false;
}

  </script>
  
  <script>
    $(document).ready(function() {
        $('#id_dt_atendimento').mask('00/00/0000');
    });
</script>







  
  
  
  
  
    
{% endblock %}